### ISSUE TITLE
Can't be deployed on OCP v4

### ISSUE THREAD

**Issue by mocenas** [snowdrop/spring-boot-cache-booster#70]
After trying to deploy cache example using:
`mvn clean fabric8:deploy -Popenshift`
on openshift v4, the deployment fails with error message:
`[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.4.0:deploy (default-cli) on project spring-boot-cache-greeting: Failed to create Route from openshift.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.ocp4.dynamic.rhoar:6443/oapi/v1/namespaces/mocenas/routes. Message: Forbidden! User rhoarqe/api-ocp4-dynamic-rhoar:6443 doesn't have permission. forbidden: User "rhoarqe" cannot post path "/oapi/v1/namespaces/mocenas/routes".. Route(apiVersion=v1, kind=Route, metadata=ObjectMeta(annotations={app.kubernetes.io/vcs-uri=git@github.com:snowdrop/cache-example.git, app.kubernetes.io/connects-to=cute-name-service}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app.kubernetes.io/part-of=cache-example, app.kubernetes.io/name=greeting-service, app.kubernetes.io/component=frontend, app.openshift.io/runtime=rh-spring-boot, app.openshift.io/runtime-version=2.3.4.RELEASE, app=spring-boot-cache-greeting, provider=fabric8, version=2.3.4-2-redhat, group=dev.snowdrop.example}, managedFields=[], name=spring-boot-cache-greeting, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=RouteSpec(alternateBackends=[], host=null, path=null, port=RoutePort(targetPort=IntOrString(IntVal=8080, Kind=0, StrVal=null, additionalProperties={}), additionalProperties={}), subdomain=null, tls=null, to=RouteTargetReference(kind=Service, name=spring-boot-cache-greeting, weight=null, additionalProperties={}), wildcardPolicy=null, additionalProperties={}), status=null, additionalProperties={}) -> [Help 1]`

The error message states something about insufficient permission, but I get this message even with cluster-admin privilege.

OCP v3 seems unaffected by this problem.

**Comment by Sgitario** [comment]
I tried to deploy using Dekorate (which replaced Fabric8) and it worked fine in OCP 3 and OCP 4 both. I tried using the `sb-2.4.x` branch. Closing.
